language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-25

    # Emulator image
    - sys-img-armeabi-v7a-android-25
