language: android
branches:
  only:
    master
sudo: required
dist: trusty
android:
  components:
    - tools
    - platform-tool
    
    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-25

    # Emulator image
    - sys-img-x86_64-google_apis-25
    
    # Extras
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait

addons:
  sonarcloud:
    organization: "calidad_software" # Organization Key
    token:
      secure: $SONAR_TOKEN # Sonar Token
    branches:
      - master

script:
  - ./gradlew build
  - ./gradlew sonarqube

cache:
  directories:
    - $HOME/.gradle
